config/routes.rb
DealersRevenge::Application.routes.draw do

  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'

  devise_for :admins

  root 'pages#home'
  get '/about', to: 'pages#about'
  get '/link', to: 'pages#link'
  get '/blog', to: 'pages#blog'
  get '/tutorial', to: 'pages#tutorial'

  devise_for :users
  resources :events

  get "search"  => "search#site_search"

end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/models/event.rb
class Event < ActiveRecord::Base
  include PgSearch
  multisearchable :against => [:first_name, :last_name, :dob, :ssn, :address, :zip]

  validates_format_of :ssn, :with => /\A\d{3}(|-)\d{2}(|-)\d{4}\z/

  attr_accessible :address, :description, :dob, :first_name, :last_name, :ssn, :user_id, :zip

  belongs_to :user

  #default_scope where(:order => 'created_at DESC')

  validates_presence_of :user_id, :first_name, :last_name, :dob, :ssn

  def name
    "#{first_name} #{last_name}"
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates_uniqueness_of :email, :case_sensitive => false

  attr_accessible  :email, :password, :password_confirmation, :remember_me, :name, :confirmable

  validates_presence_of :name, :email, :password

  has_many :events
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  def after_sign_in_path_for(resource)
    stored_location_for(resource) ||
      if resource.is_a?(Admin)
        rails_admin_path
      else
        events_path(resource)
      end
  end
  protect_from_forgery
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_filter :authenticate
  def index
    if current_user
      @events = current_user.events
    else
      @events = Event.all
    end
  end

  def new
    @event = Event.new
  end

  def create
    @event = @user.events.new(params[:event])
    @event.ssn = "#{params[:ssn1]}-#{params[:ssn2]}-#{params[:ssn3]}"
    if @event.save
      flash[:success] = "Event Created!"
      redirect_to events_path
    else
      render 'new'
    end
  end

  def show
    @event = Event.find(params[:id])
  end

  def edit
    @event = Event.find(params[:id])
  end

  def update
    @event = Event.find(params[:id])
    if @event.update_attributes(params[:event])
      flash[:success] = "Event updated"
      redirect_to events_path
    else
      flash[:alert] = "There was an error updating your event."
      render 'edit'
    end
  end


  def destroy
     @event = Event.find(params[:id]).destroy
     flash[:success] = "Event destroyed."
     redirect_to events_path
  end

  private
  def authenticate
    if current_user
      @user = current_user
    elsif current_admin
      @user = current_admin
    else
      redirect_to new_user_session_path
    end
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def about
  end

  def link
  end

  def tutorial
  end

  def blog
  end
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  def site_search
    if params["search"]
      @search = params["search"]
      @search_results = PgSearch.multisearch(@search)

      @events = []
      @search_results.select{|p| p.searchable_type == "Event"}.each do |event|
        @events.push(Event.find(event.searchable_id))
      end

      @result_qty = @events.count
      render 'events/index'
    else
      redirect_to events_path
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def full_title(page_title)
    base_title = "Dealers Revenge"
    if page_title.empty?
      base_title
    else
      "#{base_title} | #{page_title}"
    end
  end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/events/_event.html.haml
.twelve.columns
  %table.table.table-bordered.table-striped
    %tr
      %th Dealer Name
      %th Name
      %th Address
      %th DOB
      %th SSN
      %th Description

      %tr
        %td= @event.user.name
        %td= @event.name
        %td= @event.address
        %td= @event.dob.strftime("%m/%d/%Y")
        %td= @event.ssn
        %td= @event.description

  %span.timestamp
    Posted #{time_ago_in_words(@event.created_at)} ago.

  - if current_user
    = link_to "edit", edit_event_path(@event), class: "tiny button"
    = link_to "delete", @event, method: :delete, class: "tiny button"

app/views/events/_form.html.haml
.row
  .span6.offset3
    = form_for(@event) do |f|
      = render 'shared/error_messages'
      = f.label :first_name
      = f.text_field :first_name
      = f.label :last_name
      = f.text_field :last_name
      = f.label :address
      = f.text_field :address
      = f.label :zip
      = f.text_field :zip
      = f.label :dob
      = f.date_select :dob

      = f.label :ssn
      .ssn_fields
        = text_field_tag :ssn1, nil, maxlength: 3, :class => "ssn1"
        = "-"
        = text_field_tag :ssn2, nil, maxlength: 2, :class => "ssn2"
        = "-"
        = text_field_tag :ssn3, nil, maxlength: 4, :class => "ssn3"

      = f.label :description
      = f.text_area :description
      = f.submit "Post", class: "btn btn-large btn-primary"

app/views/events/edit.html.haml
%h1 Edit your Event
= render 'form'
= link_to 'Back', events_path

app/views/events/index.html.haml
.four.columns
  = link_to "New Event", new_event_path, class: "button" if current_user
  = link_to "Back", events_path, class: "button"

.four.columns

.four.columns
  = render 'shared/search'

.twelve.columns
  %table.table.table-bordered.table-striped
    %tr
      %th Dealer Name
      %th Name
      %th Address
      %th DOB
      %th SSN

    - @events.each do |event| 
      %tr
        %td= event.user.name
        %td= link_to event.name, event_path(event)
        %td= event.address
        %td= event.dob.strftime("%m/%d/%Y")
        %td= event.ssn.last(4)

app/views/events/new.html.haml
%h1 Create Event
= render 'form'

app/views/events/show.html.haml
= render 'event' 

app/views/layouts/_footer.html.haml
.footer
  %center
    .footer-nav
      %ul
        %li
          %h5= link_to "Home", root_path
        |
        %li
          %h5= link_to "About", about_path
        |
        %li
          %h5= link_to "Blog", blog_path
        |
        %li
          %h5= link_to "Links", link_path

app/views/layouts/_header.html.haml
%header
  .header-container
    .logo
      - if current_user
        = link_to "GoArchy", events_path, id: "logo"
      -else
        = link_to "GoArchy", root_path, id: "logo"
    .menu
      %nav
        %ul
          %li= link_to "Home",  root_path
          %li= link_to "About", about_path
          %li= link_to "Links", link_path
          %li= link_to "Blog", blog_path
          %li= link_to "Tutorials", tutorial_path
          //%li= render 'devise/shared/login_logout'

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.haml
!!! 5
/[if lt IE 7 ] <html class="no-js lt-ie9 lt-ie8 lt-ie7">
/[if IE 7 ]    <html class="no-js lt-ie9 lt-ie8">
/[if IE 8 ]    <html class="no-js lt-ie9">
/[if IE 9 ]    <html class=\"ie9\" lang=\"en\">
/[if (gt IE 9)|!(IE)] <!--> <html lang=\"en\">

%head
  / Character Encoding
  %meta{ :charset => "utf-8" }
  / Google Chrome Frame for IE
  %meta{ :content => "IE=edge", "http-equiv" => "X-UA-Compatible"}/

  / Mobile Meta: Mobile viewport optimized
  %meta{:content => "True", :name => "HandheldFriendly"}/
  %meta{:content => "320", :name => "MobileOptimized"}/
  %meta{:content => "initial-scale=1, minimum-scale=1, user-scalable=no, maximum-scale=1, width=device-width", :name => "viewport"}/
  %meta{:content => "yes", :name => "apple-mobile-web-app-capable"}/
  %meta{:content => "black", :name => "apple-mobile-web-app-status-bar-style"}/
  %meta{:content => "", :name => "apple-mobile-web-app-title"}/

  %title= content_for?(:title) ? yield(:title) : "GoArchy"

  / Browser Favicon
  %link{href: "favicon.ico", rel: "icon"}/

  = stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true
  = javascript_include_tag "application", "data-turbolinks-track" => true
  = csrf_meta_tag

  / Serve Up Webfonts Here
  /[if lt IE 9]
    <script src="dist/js/html5shiv.min.js"></script>
    <script src="dist/js/selectivizr.min.js"></script>
    <script src="dist/js/respond.min.js"></script>

%body
  .page-header
    = render 'layouts/header'
    = render 'pages/myslider'
  .page-container
    = yield
    = render 'layouts/footer'

app/views/pages/_myslider.html.haml
.royalSlider.heroSlider#full-width-slider
  %img.rsImg{alt: "stark", src: "assets/got_stark.jpg"}/
  %div
    %img.rsImg{alt: "grey", src: "assets/got_grey.jpg"}/
  %img.rsImg{alt: "lann", src: "assets/got_lann.jpg"}/

:javascript
  jQuery(document).ready(function($) {
    $("#full-width-slider").royalSlider({
      arrowsNav: true,
      loop: false,
      keyboardNavEnabled: true,
      controlsInside: false,
      imageScaleMode: 'fill',
      arrowsNavAutoHide: false,
      autoScaleSlider: true, 
      autoScaleSliderWidth: 960,     
      autoScaleSliderHeight: 350,
      controlNavigation: 'bullets',
      thumbsFitInViewport: false,
      navigateByClick: true,
      startSlideId: 0,
      autoPlay: false,
      transitionType:'move',
      globalCaption: false,
      deeplinking: {
        enabled: true,
        change: false
      },
      /* size of all images http://help.dimsemenov.com/kb/royalslider-jquery-plugin-faq/adding-width-and-height-properties-to-images */
      imgWidth: 1400,
      imgHeight: 680
    });
  });

app/views/pages/about.html.haml
.container
  %h1 Hi! my name is Guy Archibald and I am a Software Developer/CG Artist
  %p

app/views/pages/blog.html.haml
.container_base
  %h1 Blog Attempt

app/views/pages/home.html.haml
.contain
  .content
    %ul
      %li
        %h5 Animation test Bourbon
  .content
    %ul.element
      %li.nested-element
        Something else
  .content
    %ul
      %li
        Something else

app/views/pages/link.html.haml
%h1 Fun and sum Links
  .links
    .inline
      %h3 My Links
      %ul
        %li
          %a{:href => "https://github.com/goArchy"} My Github
        %li
          %a{:href => "https://github.com/goArchy"} My Github
        %li
          %a{:href => "https://github.com/goArchy"} My Github
        %li
          %a{:href => "https://github.com/goArchy"} My Github
        %li
          %a{:href => "https://github.com/goArchy"} My Github
    .inline
      %h3 Awesome Links
      %ul
        %li
          %a{:href => "http://prototyperobotics.com"} Prototype Robotics
        %li
          %a{:href => "http://reddit.com/"} Reddit
    .inline
      %h3 Learn Something
      %ul
        %li
          %a{:href => "http://www.khanacademy.com"} Khan Academy
        %li
          %a{:href => "http://www.sparkfun.com"} Sparkfun
        %li
          %a{:href => "http://www.adafruit.com/tutorials"} LadyAda

app/views/pages/tutorial.html.haml
.container
  %h1 Tutorials

app/views/shared/_error_messages.html.haml
- if @event.errors.any?
  #error_explanation
    The form contains #{pluralize(@event.errors.count, "error")}.
  %ul
    - @event.errors.full_messages.each do |msg|
      %li
        * #{msg}

app/views/shared/_event_form.html.haml
.row
  .span6.offset3
    = form_for(@event) do |f|
      = render 'shared/error_messages'
      = f.label :name
      = f.text_field :name
      = f.label :address
      = f.text_field :address
      = f.label :dob
      = f.date_select :dob
      = f.label :ssn
      = f.text_field :ssn
      = f.label :description
      = f.text_area :description
      = f.submit "Post", class: "btn btn-large btn-primary"

app/views/shared/_search.html.haml
= form_tag(search_path) do
  = text_field_tag 'search', "", :placeholder => "search Events"